# 01 · Data Understanding

**Project:** Enterprise HR AI  
**Purpose:** Read-only profiling of all 7 raw datasets.  
**Rule:** No merging, cleaning, or dropping anything in this notebook.

---

## Datasets covered
| # | File |
|---|------|
| 1 | `employee_attrition.csv` |
| 2 | `occupation_data.csv` |
| 3 | `essential_skills.csv` |
| 4 | `software_skills.csv` |
| 5 | `Cleaned_HR_Data_Analysis.csv` |
| 6 | `Employee_Performance_Dataset.csv` |
| 7 | `employee_performance_pro.csv` |

In [1]:
import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 60)
pd.set_option('display.float_format', '{:.2f}'.format)

RAW = os.path.join('..', 'data', 'raw')
print('Raw data path:', os.path.abspath(RAW))
print('Files present:', os.listdir(RAW))

Raw data path: C:\Users\ASUS\Desktop\enterprise_hr_ai\data\raw
Files present: ['Cleaned_HR_Data_Analysis.csv', 'employee_attrition.csv', 'Employee_Performance_Dataset.csv', 'employee_performance_pro.csv', 'essential_skills.csv', 'occupation_data.csv', 'software_skills.csv']

---
## 1 · employee_attrition.csv

In [2]:
attrition = pd.read_csv(os.path.join(RAW, 'employee_attrition.csv'))
print('=== employee_attrition.csv ===')

=== employee_attrition.csv ===

In [3]:
# 1. Shape
print('Shape:', attrition.shape)

Shape: (1470, 35)

In [4]:
# 2. Head
attrition.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [5]:
# 3. Info
attrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
# 4. Null counts sorted descending
nulls = attrition.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
No nulls found

In [7]:
# 5. Duplicate rows
print('Duplicate rows:', attrition.duplicated().sum())

Duplicate rows: 0

In [8]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in attrition.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {attrition[c].nunique()} unique values, sample:', attrition[c].dropna().head(5).tolist())

ID-like columns: []

In [9]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in attrition.columns:
    n = attrition[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(attrition[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [Attrition] (2 unique):
  ['No', 'Yes']

  [BusinessTravel] (3 unique):
  ['Non-Travel', 'Travel_Frequently', 'Travel_Rarely']

  [Department] (3 unique):
  ['Human Resources', 'Research & Development', 'Sales']

  [Education] (5 unique):
  [1, 2, 3, 4, 5]

  [EducationField] (6 unique):
  ['Human Resources', 'Life Sciences', 'Marketing', 'Medical', 'Other', 'Technical Degree']

  [EmployeeCount] (1 unique):
  [1]

  [EnvironmentSatisfaction] (4 unique):
  [1, 2, 3, 4]

  [Gender] (2 unique):
  ['Female', 'Male']

  [JobInvolvement] (4 unique):
  [1, 2, 3, 4]

  [JobLevel] (5 unique):
  [1, 2, 3, 4, 5]

  [JobRole] (9 unique):
  ['Healthcare Representative', 'Human Resources', 'Laboratory Technician', 'Manager', 'Manufacturing Director', 'Research Director', 'Research Scientist', 'Sales Executive', 'Sales Representative']

  [JobSatisfaction] (4 unique):
  [1, 2, 3, 4]

  [MaritalStatus] (3 unique):
  ['Divorced', 'Married', 'Single']

  [NumCompaniesWorked] (10 unique):
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

  [Over18] (1 unique):
  ['Y']

  [OverTime] (2 unique):
  ['No', 'Yes']

  [PercentSalaryHike] (15 unique):
  [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

  [PerformanceRating] (2 unique):
  [3, 4]

  [RelationshipSatisfaction] (4 unique):
  [1, 2, 3, 4]

  [StandardHours] (1 unique):
  [80]

  [StockOptionLevel] (4 unique):
  [0, 1, 2, 3]

  [TrainingTimesLastYear] (7 unique):
  [0, 1, 2, 3, 4, 5, 6]

  [WorkLifeBalance] (4 unique):
  [1, 2, 3, 4]

  [YearsInCurrentRole] (19 unique):
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

  [YearsSinceLastPromotion] (16 unique):
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

  [YearsWithCurrManager] (18 unique):
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]

In [10]:
# ATTRITION-SPECIFIC: Class balance check
print('=== Attrition Class Balance ===')
balance = attrition['Attrition'].value_counts(normalize=True) * 100
print(balance.to_string())
print(f'\nRaw counts:\n{attrition["Attrition"].value_counts().to_string()}')

=== Attrition Class Balance ===
Attrition
No    83.88
Yes   16.12

Raw counts:
Attrition
No     1233
Yes     237

---
## 2 · occupation_data.csv

In [11]:
occ = pd.read_csv(os.path.join(RAW, 'occupation_data.csv'))
print('=== occupation_data.csv ===')

=== occupation_data.csv ===

In [12]:
# 1. Shape
print('Shape:', occ.shape)

Shape: (1016, 3)

In [13]:
# 2. Head
occ.head()

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide overall dir...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, shareholders..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of public or ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes at the lo..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising policies and pro..."

In [14]:
# 3. Info
occ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016 entries, 0 to 1015
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   O*NET-SOC Code  1016 non-null   object
 1   Title           1016 non-null   object
 2   Description     1016 non-null   object
dtypes: object(3)
memory usage: 23.9+ KB

In [15]:
# 4. Null counts sorted descending
nulls = occ.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
No nulls found

In [16]:
# 5. Duplicate rows
print('Duplicate rows:', occ.duplicated().sum())

Duplicate rows: 0

In [17]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in occ.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {occ[c].nunique()} unique values, sample:', occ[c].dropna().head(5).tolist())

ID-like columns: []

In [18]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in occ.columns:
    n = occ[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(occ[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

---
## 3 · essential_skills.csv

In [19]:
ess = pd.read_csv(os.path.join(RAW, 'essential_skills.csv'))
print('=== essential_skills.csv ===')

=== essential_skills.csv ===

In [20]:
# 1. Shape
print('Shape:', ess.shape)

Shape: (18200, 15)

In [21]:
# 2. Head
ess.head()

,O*NET-SOC Code,Title,Element ID,Element Name,Scale ID,Scale Name,Data Value,N,Standard Error,Lower CI Bound,Upper CI Bound,Recommend Suppress,Not Relevant,Date,Domain Source
0,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,IM,Importance,4.12,8,0.12,3.88,4.37,N,NaN,08/2023,Analyst
1,11-1011.00,Chief Executives,2.A.1.a,Reading Comprehension,LV,Level,4.62,8,0.18,4.27,4.98,N,N,08/2023,Analyst
2,11-1011.00,Chief Executives,2.A.1.b,Active Listening,IM,Importance,4.00,8,0.00,4.00,4.00,N,NaN,08/2023,Analyst
3,11-1011.00,Chief Executives,2.A.1.b,Active Listening,LV,Level,4.75,8,0.16,4.43,5.07,N,N,08/2023,Analyst
4,11-1011.00,Chief Executives,2.A.1.c,Writing,IM,Importance,4.12,8,0.12,3.88,4.37,N,NaN,08/2023,Analyst

In [22]:
# 3. Info
ess.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18200 entries, 0 to 18199
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   O*NET-SOC Code      18200 non-null  object
 1   Title               18200 non-null  object
 2   Element ID          18200 non-null  object
 3   Element Name        18200 non-null  object
 4   Scale ID            18200 non-null  object
 5   Scale Name          18200 non-null  object
 6   Data Value          18200 non-null  float64
 7   N                   18200 non-null  int64
 8   Standard Error      18200 non-null  float64
 9   Lower CI Bound      18200 non-null  float64
 10  Upper CI Bound      18200 non-null  float64
 11  Recommend Suppress  18200 non-null  object
 12  Not Relevant        9100 non-null   object
 13  Date                18200 non-null  object
 14  Domain Source       18200 non-null  object
dtypes: float64(4), int64(1), object(10)
memory usage: 2.1+ MB

In [23]:
# 4. Null counts sorted descending
nulls = ess.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
Not Relevant    9100
dtype: int64

In [24]:
# 5. Duplicate rows
print('Duplicate rows:', ess.duplicated().sum())

Duplicate rows: 0

In [25]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in ess.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {ess[c].nunique()} unique values, sample:', ess[c].dropna().head(5).tolist())

ID-like columns: ['Element ID', 'Scale ID']
  Element ID: 10 unique values, sample: ['2.A.1.a', '2.A.1.a', '2.A.1.b', '2.A.1.b', '2.A.1.c']
  Scale ID: 2 unique values, sample: ['IM', 'LV', 'IM', 'LV', 'IM']

In [26]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in ess.columns:
    n = ess[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(ess[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [Element ID] (10 unique):
  ['2.A.1.a', '2.A.1.b', '2.A.1.c', '2.A.1.d', '2.A.1.e', '2.A.1.f', '2.A.2.a', '2.A.2.b', '2.A.2.c', '2.A.2.d']

  [Element Name] (10 unique):
  ['Active Learning', 'Active Listening', 'Critical Thinking', 'Learning Strategies', 'Mathematics', 'Monitoring', 'Reading Comprehension', 'Science', 'Speaking', 'Writing']

  [Scale ID] (2 unique):
  ['IM', 'LV']

  [Scale Name] (2 unique):
  ['Importance', 'Level']

  [N] (1 unique):
  [8]

  [Recommend Suppress] (2 unique):
  ['N', 'Y']

  [Not Relevant] (2 unique):
  ['N', 'Y']

  [Date] (17 unique):
  ['06/2010', '07/2011', '07/2012', '07/2013', '07/2014', '07/2015', '07/2016', '07/2017', '08/2018', '08/2019', '08/2020', '08/2021', '08/2022', '08/2023', '08/2024', '08/2025', '08/2026']

  [Domain Source] (1 unique):
  ['Analyst']

---
## 4 · software_skills.csv

In [27]:
sw = pd.read_csv(os.path.join(RAW, 'software_skills.csv'))
print('=== software_skills.csv ===')

=== software_skills.csv ===

In [28]:
# 1. Shape
print('Shape:', sw.shape)

Shape: (31821, 7)

In [29]:
# 2. Head
sw.head()

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,2.E.6.c,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,2.E.2.a,Accounting software,N,N

In [30]:
# 3. Info
sw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31821 entries, 0 to 31820
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   O*NET-SOC Code     31821 non-null  object
 1   Title              31821 non-null  object
 2   Workplace Example  31821 non-null  object
 3   Element ID         31821 non-null  object
 4   Element Name       31821 non-null  object
 5   Hot Technology     31821 non-null  object
 6   In Demand          31821 non-null  object
dtypes: object(7)
memory usage: 1.7+ MB

In [31]:
# 4. Null counts sorted descending
nulls = sw.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
No nulls found

In [32]:
# 5. Duplicate rows
print('Duplicate rows:', sw.duplicated().sum())

Duplicate rows: 0

In [33]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in sw.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {sw[c].nunique()} unique values, sample:', sw[c].dropna().head(5).tolist())

ID-like columns: ['Element ID']
  Element ID: 134 unique values, sample: ['2.E.5.b', '2.E.6.f', '2.E.5.a', '2.E.6.c', '2.E.2.a']

In [34]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in sw.columns:
    n = sw[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(sw[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [Hot Technology] (2 unique):
  ['N', 'Y']

  [In Demand] (2 unique):
  ['N', 'Y']

---
## 5 · Cleaned_HR_Data_Analysis.csv

In [35]:
hr_clean = pd.read_csv(os.path.join(RAW, 'Cleaned_HR_Data_Analysis.csv'))
print('=== Cleaned_HR_Data_Analysis.csv ===')

=== Cleaned_HR_Data_Analysis.csv ===

In [36]:
# 1. Shape
print('Shape:', hr_clean.shape)

Shape: (2845, 28)

In [37]:
# 2. Head
hr_clean.head()

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,DOB,State,GenderCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating,Survey Date,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,07-10-1969,MA,Female,White,Widowed,Fully Meets,4,14-01-2023,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,30-08-1965,MA,Male,Hispanic,Widowed,Fully Meets,3,09-09-2022,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
2,3429,10-Dec-18,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,06-10-1991,MA,Male,Hispanic,Widowed,Fully Meets,4,27-05-2023,1,2,1,13-Aug-22,Leadership Development,External,Failed,2,413.28,27
3,3430,21-Jun-21,Area Sales Manager,CCDR,Active,Contract,Zone A,Full-Time,Sales,Finance & Accounting,04-04-1998,ND,Male,Other,Single,Fully Meets,2,16-06-2023,5,5,4,15-Dec-22,Project Management,External,Completed,3,663.78,23
4,3431,29-Jun-19,Area Sales Manager,TNS,Active,Contract,Zone A,Temporary,Sales,General - Con,29-08-1969,FL,Female,Other,Married,Fully Meets,3,25-11-2022,2,5,3,13-Jul-23,Technical Skills,External,Failed,5,399.03,50

In [38]:
# 3. Info
hr_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2845 entries, 0 to 2844
Data columns (total 28 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 2845 non-null   int64
 1   StartDate                   2845 non-null   object
 2   Title                       2845 non-null   object
 3   BusinessUnit                2845 non-null   object
 4   EmployeeStatus              2845 non-null   object
 5   EmployeeType                2845 non-null   object
 6   PayZone                     2845 non-null   object
 7   EmployeeClassificationType  2845 non-null   object
 8   DepartmentType              2845 non-null   object
 9   Division                    2845 non-null   object
 10  DOB                         2845 non-null   object
 11  State                       2845 non-null   object
 12  GenderCode                  2845 non-null   object
 13  RaceDesc                    2845 non-null   object
 14  MaritalDesc                 2845 non-null   object
 15  Performance Score           2845 non-null   object
 16  Current Employee Rating     2845 non-null   int64
 17  Survey Date                 2845 non-null   object
 18  Engagement Score            2845 non-null   int64
 19  Satisfaction Score          2845 non-null   int64
 20  Work-Life Balance Score     2845 non-null   int64
 21  Training Date               2845 non-null   object
 22  Training Program Name       2845 non-null   object
 23  Training Type               2845 non-null   object
 24  Training Outcome            2845 non-null   object
 25  Training Duration(Days)     2845 non-null   int64
 26  Training Cost               2845 non-null   float64
 27  Age                         2845 non-null   int64
dtypes: float64(1), int64(7), object(20)
memory usage: 622.5+ KB

In [39]:
# 4. Null counts sorted descending
nulls = hr_clean.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
No nulls found

In [40]:
# 5. Duplicate rows
print('Duplicate rows:', hr_clean.duplicated().sum())

Duplicate rows: 0

In [41]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in hr_clean.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {hr_clean[c].nunique()} unique values, sample:', hr_clean[c].dropna().head(5).tolist())

ID-like columns: ['Employee ID']
  Employee ID: 2845 unique values, sample: [3427, 3428, 3429, 3430, 3431]

In [42]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in hr_clean.columns:
    n = hr_clean[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(hr_clean[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [BusinessUnit] (10 unique):
  ['BPC', 'CCDR', 'EW', 'MSC', 'NEL', 'PL', 'PYZ', 'SVG', 'TNS', 'WBL']

  [EmployeeStatus] (2 unique):
  ['Active', 'Terminated']

  [EmployeeType] (3 unique):
  ['Contract', 'Full-Time', 'Part-Time']

  [PayZone] (3 unique):
  ['Zone A', 'Zone B', 'Zone C']

  [EmployeeClassificationType] (3 unique):
  ['Full-Time', 'Part-Time', 'Temporary']

  [DepartmentType] (6 unique):
  ['Admin Offices', 'Executive Office', 'IT/IS', 'Production       ', 'Sales', 'Software Engineering']

  [GenderCode] (2 unique):
  ['Female', 'Male']

  [RaceDesc] (5 unique):
  ['Asian', 'Black', 'Hispanic', 'Other', 'White']

  [MaritalDesc] (4 unique):
  ['Divorced', 'Married', 'Single', 'Widowed']

  [Performance Score] (4 unique):
  ['Exceeds', 'Fully Meets', 'Needs Improvement', 'PIP']

  [Current Employee Rating] (5 unique):
  [1, 2, 3, 4, 5]

  [Engagement Score] (5 unique):
  [1, 2, 3, 4, 5]

  [Satisfaction Score] (5 unique):
  [1, 2, 3, 4, 5]

  [Work-Life Balance Score] (5 unique):
  [1, 2, 3, 4, 5]

  [Training Program Name] (5 unique):
  ['Communication Skills', 'Customer Service', 'Leadership Development', 'Project Management', 'Technical Skills']

  [Training Type] (2 unique):
  ['External', 'Internal']

  [Training Outcome] (4 unique):
  ['Completed', 'Failed', 'Incomplete', 'Passed']

  [Training Duration(Days)] (5 unique):
  [1, 2, 3, 4, 5]

---
## 6 · Employee_Performance_Dataset.csv

In [43]:
perf_ds = pd.read_csv(os.path.join(RAW, 'Employee_Performance_Dataset.csv'))
print('=== Employee_Performance_Dataset.csv ===')

=== Employee_Performance_Dataset.csv ===

In [44]:
# 1. Shape
print('Shape:', perf_ds.shape)

Shape: (5000, 13)

In [45]:
# 2. Head
perf_ds.head()

,Employee ID,Name,Department,Job Role,Performance Score,KPI Score,Attendance (%),Peer Rating,Task Completion (%),Work Hours Logged,Manager Feedback,Training Hours,Promotion Eligibility
0,376063,Manikya Badami,Sales,Sales Executive,61,91.03,94.40,4.50,78.19,42,3.70,18,No
1,810690,Zara Mahal,Marketing,Marketing Executive,91,83.36,78.45,4.70,71.39,46,4.50,15,Yes
2,520956,Sana Gera,Finance,Accountant,100,65.39,99.50,4.40,80.20,51,3.50,7,No
3,202996,Zoya Wadhwa,Marketing,Content Strategist,100,82.90,79.83,4.30,71.51,43,5.00,9,Yes
4,383410,Baiju Doctor,Sales,Sales Executive,80,90.90,89.92,3.70,78.03,51,3.10,29,No

In [46]:
# 3. Info
perf_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee ID            5000 non-null   int64
 1   Name                   5000 non-null   object
 2   Department             5000 non-null   object
 3   Job Role               5000 non-null   object
 4   Performance Score      5000 non-null   int64
 5   KPI Score              5000 non-null   float64
 6   Attendance (%)         5000 non-null   float64
 7   Peer Rating            5000 non-null   float64
 8   Task Completion (%)    5000 non-null   float64
 9   Work Hours Logged      5000 non-null   int64
 10  Manager Feedback       5000 non-null   float64
 11  Training Hours         5000 non-null   int64
 12  Promotion Eligibility  5000 non-null   object
dtypes: float64(5), int64(4), object(4)
memory usage: 507.9+ KB

In [47]:
# 4. Null counts sorted descending
nulls = perf_ds.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
No nulls found

In [48]:
# 5. Duplicate rows
print('Duplicate rows:', perf_ds.duplicated().sum())

Duplicate rows: 0

In [49]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in perf_ds.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {perf_ds[c].nunique()} unique values, sample:', perf_ds[c].dropna().head(5).tolist())

ID-like columns: ['Employee ID']
  Employee ID: 5000 unique values, sample: [376063, 810690, 520956, 202996, 383410]

In [50]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in perf_ds.columns:
    n = perf_ds[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(perf_ds[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [Department] (5 unique):
  ['Finance', 'HR', 'IT', 'Marketing', 'Sales']

  [Job Role] (15 unique):
  ['Account Manager', 'Accountant', 'Auditor', 'Business Development', 'Content Strategist', 'Cybersecurity Specialist', 'Data Analyst', 'Employee Relations', 'Financial Analyst', 'HR Manager', 'Marketing Executive', 'Recruitment Specialist', 'SEO Specialist', 'Sales Executive', 'Software Engineer']

  [Promotion Eligibility] (2 unique):
  ['No', 'Yes']

---
## 7 · employee_performance_pro.csv

In [51]:
perf_pro = pd.read_csv(os.path.join(RAW, 'employee_performance_pro.csv'))
print('=== employee_performance_pro.csv ===')

=== employee_performance_pro.csv ===

In [52]:
# 1. Shape
print('Shape:', perf_pro.shape)

Shape: (500, 24)

In [53]:
# 2. Head
perf_pro.head()

,EmployeeID,Name,Gender,Age,Department,JobRole,EducationLevel,JoiningDate,CountryCode,Country,PhoneNumber,MonthlySalary,OvertimeHoursPerMonth,LeavesTaken,LastLeaveDate,LeaveDayName,ProjectsHandled,TrainingHours,CustomerSatisfaction,LastPromotionYear,YearsAtCompany,WorkLifeBalanceScore,PerformanceRating,AttritionRisk
0,1,Steven Barnett,Other,57,Finance,Auditor,2,2016-05-05,91,India,6222371166,93531,33,9,2024-07-03,Wednesday,13,16,NaN,2020,9,1.90,4,No
1,2,Christopher Benson,Female,26,Sales,Sales Executive,2,2014-08-20,1,Canada,466649099,53706,24,1,2024-01-05,Friday,15,44,8.00,2014,11,5.03,1,Yes
2,3,Norman Lane,Other,59,Support,Helpdesk,1,2010-05-17,1,Canada,8302098565,105756,20,7,2024-11-27,Wednesday,7,62,7.00,2012,15,4.83,4,No
3,4,Rita Walker,Female,43,HR,HR Executive,3,2015-06-20,49,Germany,5555799735,176377,22,6,2024-07-15,Monday,15,8,NaN,2016,10,4.60,4,No
4,5,Judith Ware,Male,52,Sales,Account Manager,3,2019-08-20,49,Germany,4796634990,154782,18,16,2024-12-17,Tuesday,10,57,8.00,2022,6,3.73,4,No

In [54]:
# 3. Info
perf_pro.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   EmployeeID             500 non-null    int64
 1   Name                   500 non-null    object
 2   Gender                 500 non-null    object
 3   Age                    500 non-null    int64
 4   Department             500 non-null    object
 5   JobRole                500 non-null    object
 6   EducationLevel         500 non-null    int64
 7   JoiningDate            500 non-null    object
 8   CountryCode            500 non-null    int64
 9   Country                500 non-null    object
 10  PhoneNumber            500 non-null    int64
 11  MonthlySalary          500 non-null    int64
 12  OvertimeHoursPerMonth  500 non-null    int64
 13  LeavesTaken            500 non-null    int64
 14  LastLeaveDate          500 non-null    object
 15  LeaveDayName           500 non-null    object
 16  ProjectsHandled        500 non-null    int64
 17  TrainingHours          500 non-null    int64
 18  CustomerSatisfaction   181 non-null    float64
 19  LastPromotionYear      500 non-null    int64
 20  YearsAtCompany         500 non-null    int64
 21  WorkLifeBalanceScore   500 non-null    float64
 22  PerformanceRating      500 non-null    int64
 23  AttritionRisk          500 non-null    object
dtypes: float64(2), int64(13), object(9)
memory usage: 93.9+ KB

In [55]:
# 4. Null counts sorted descending
nulls = perf_pro.isnull().sum().sort_values(ascending=False)
print('Null counts (sorted):')
print(nulls[nulls > 0] if nulls.max() > 0 else 'No nulls found')

Null counts (sorted):
CustomerSatisfaction    319
dtype: int64

In [56]:
# 5. Duplicate rows
print('Duplicate rows:', perf_pro.duplicated().sum())

Duplicate rows: 0

In [57]:
# 6. Candidate join keys - columns containing 'id' (case-insensitive)
id_cols = [c for c in perf_pro.columns if 'id' in c.lower()]
print('ID-like columns:', id_cols)
for c in id_cols:
    print(f'  {c}: {perf_pro[c].nunique()} unique values, sample:', perf_pro[c].dropna().head(5).tolist())

ID-like columns: ['EmployeeID']
  EmployeeID: 500 unique values, sample: [1, 2, 3, 4, 5]

In [58]:
# 7. Categorical columns (< 20 unique values)
print('Categorical columns (< 20 unique values):')
for col in perf_pro.columns:
    n = perf_pro[col].nunique()
    if n < 20:
        print(f'\n  [{col}] ({n} unique):')
        print(f'  {sorted(perf_pro[col].dropna().unique().tolist())}')

Categorical columns (< 20 unique values):

  [Gender] (3 unique):
  ['Female', 'Male', 'Other']

  [Department] (6 unique):
  ['Finance', 'HR', 'IT', 'Marketing', 'Sales', 'Support']

  [JobRole] (13 unique):
  ['Account Manager', 'Accountant', 'Auditor', 'Content Lead', 'Developer', 'Engineer', 'HR Executive', 'HR Manager', 'Helpdesk', 'SEO Analyst', 'Sales Executive', 'Support Engineer', 'Tester']

  [EducationLevel] (5 unique):
  [1, 2, 3, 4, 5]

  [CountryCode] (5 unique):
  [1, 33, 44, 49, 91]

  [Country] (6 unique):
  ['Canada', 'France', 'Germany', 'India', 'UK', 'USA']

  [LeaveDayName] (7 unique):
  ['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

  [ProjectsHandled] (15 unique):
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

  [CustomerSatisfaction] (10 unique):
  [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

  [LastPromotionYear] (15 unique):
  [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

  [YearsAtCompany] (14 unique):
  [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

  [PerformanceRating] (5 unique):
  [1, 2, 3, 4, 5]

  [AttritionRisk] (2 unique):
  ['No', 'Yes']

---
## Cross-File Comparison: Performance Files vs. employee_attrition.csv

> **Read-only analysis.** No merges, no drops. We are only checking whether join keys actually overlap.

The three performance-shaped files are:
- `Cleaned_HR_Data_Analysis.csv` -> `hr_clean`
- `Employee_Performance_Dataset.csv` -> `perf_ds`
- `employee_performance_pro.csv` -> `perf_pro`

We compare each against `employee_attrition.csv` (`attrition`) on:
1. Row counts
2. ID-overlap with `attrition['EmployeeNumber']` (set intersection - no name-similarity assumptions)
3. Engagement/satisfaction-relevant column richness

In [59]:
# STEP A: Row-count comparison
print('=== ROW COUNT COMPARISON ===')
frames = {
    'employee_attrition':           attrition,
    'Cleaned_HR_Data_Analysis':     hr_clean,
    'Employee_Performance_Dataset': perf_ds,
    'employee_performance_pro':     perf_pro,
}
for name, df in frames.items():
    print(f'  {name:42s}  rows={df.shape[0]:>6,}  cols={df.shape[1]:>3}')

=== ROW COUNT COMPARISON ===
  employee_attrition                          rows= 1,470  cols= 35
  Cleaned_HR_Data_Analysis                    rows= 2,845  cols= 28
  Employee_Performance_Dataset                rows= 5,000  cols= 13
  employee_performance_pro                    rows=   500  cols= 24

In [60]:
# STEP B: ID-overlap check
# Each performance file is tested against attrition['EmployeeNumber'].
# We do NOT assume column names match; we test EVERY ID-like column
# in each performance file via set intersection.

# Determine the anchor set from attrition
if 'EmployeeNumber' in attrition.columns:
    anchor_col = 'EmployeeNumber'
else:
    id_candidates = [c for c in attrition.columns if 'id' in c.lower()]
    anchor_col = id_candidates[0] if id_candidates else None
    if anchor_col:
        print(f'WARNING: EmployeeNumber not found in attrition -- using "{anchor_col}" as anchor instead.')

overlap_results = {}

if anchor_col:
    anchor_vals = set(attrition[anchor_col].dropna().astype(str))
    anchor_n    = len(anchor_vals)
    print(f'Anchor: attrition["{anchor_col}"]  --> {anchor_n} unique values')
    print()

    perf_frames = {
        'Cleaned_HR_Data_Analysis':     hr_clean,
        'Employee_Performance_Dataset': perf_ds,
        'employee_performance_pro':     perf_pro,
    }

    print('=== ID OVERLAP CHECK (set intersection, no name-similarity assumptions) ===')

    for fname, df in perf_frames.items():
        print(f'\n--- {fname} ---')
        id_like = [c for c in df.columns if 'id' in c.lower()]

        if not id_like:
            print(f'  No ID-like columns found. Overlap cannot be computed.')
            overlap_results[fname] = []
            continue

        file_results = []
        for col in id_like:
            candidate_vals = set(df[col].dropna().astype(str))
            intersection   = anchor_vals & candidate_vals
            n_overlap      = len(intersection)
            pct_of_anchor  = (n_overlap / anchor_n       * 100) if anchor_n       else 0.0
            pct_of_cand    = (n_overlap / len(candidate_vals) * 100) if candidate_vals else 0.0
            file_results.append({
                'perf_col':               col,
                'n_unique_in_perf_file':  len(candidate_vals),
                'overlap_count':          n_overlap,
                'pct_of_attrition_anchor': round(pct_of_anchor, 2),
                'pct_of_perf_col':        round(pct_of_cand, 2),
            })
            print(f'  {col:38s}  n_unique={len(candidate_vals):>6}  '
                  f'overlap={n_overlap:>5}  '
                  f'(%attrition={pct_of_anchor:5.1f}%  %perf_col={pct_of_cand:5.1f}%)')
        overlap_results[fname] = file_results
else:
    print('Cannot compute ID overlap -- no usable anchor column found in attrition.')

Anchor: attrition["EmployeeNumber"]  --> 1470 unique values

=== ID OVERLAP CHECK (set intersection, no name-similarity assumptions) ===

--- Cleaned_HR_Data_Analysis ---
  Employee ID                             n_unique=  2845  overlap=  731  (%attrition= 49.7%  %perf_col= 25.7%)

--- Employee_Performance_Dataset ---
  Employee ID                             n_unique=  5000  overlap=    0  (%attrition=  0.0%  %perf_col=  0.0%)

--- employee_performance_pro ---
  EmployeeID                              n_unique=   500  overlap=  377  (%attrition= 25.6%  %perf_col= 75.4%)

In [61]:
# STEP C: Engagement / satisfaction column richness
# Keywords drawn from HR literature
ENGAGEMENT_KEYWORDS = [
    'satisf', 'engage', 'wellb', 'morale', 'motivat',
    'burnout', 'commit', 'nps', 'survey', 'sentiment',
    'happi', 'loyal', 'retention', 'turnover', 'balance',
    'environment', 'relation', 'climate',
]

def count_engagement_cols(df):
    matched = [c for c in df.columns
               if any(kw in c.lower() for kw in ENGAGEMENT_KEYWORDS)]
    return matched

print('=== ENGAGEMENT / SATISFACTION COLUMN RICHNESS ===')
for fname, df in {
    'Cleaned_HR_Data_Analysis':     hr_clean,
    'Employee_Performance_Dataset': perf_ds,
    'employee_performance_pro':     perf_pro,
}.items():
    matched = count_engagement_cols(df)
    print(f'\n  {fname}  -->  {len(matched)} engagement-related column(s):')
    if matched:
        for c in matched:
            print(f'    * {c}')
    else:
        print('    (none matched)')

=== ENGAGEMENT / SATISFACTION COLUMN RICHNESS ===

  Cleaned_HR_Data_Analysis  -->  4 engagement-related column(s):
    * Survey Date
    * Engagement Score
    * Satisfaction Score
    * Work-Life Balance Score

  Employee_Performance_Dataset  -->  0 engagement-related column(s):
    (none matched)

  employee_performance_pro  -->  2 engagement-related column(s):
    * CustomerSatisfaction
    * WorkLifeBalanceScore

---
## Final Summary & Recommendation

> **Read-only analysis complete.** The table and recommendation below are based solely on evidence gathered in this notebook. No merges or cleaning have been performed.

### Dataset Summary Table

*(Programmatic table is generated in the next cell from live data.  
The static table below acts as a reference skeleton.)*

| # | Dataset | Rows | Cols | Likely Primary Key | Top Missing Col (% miss) | Purpose |
|---|---------|------|------|-------------------|--------------------------|---------|
| 1 | `employee_attrition.csv` | — | — | `EmployeeNumber` | — | Attrition target + HR features (**anchor**) |
| 2 | `occupation_data.csv` | — | — | O*NET / SOC code | — | External occupation-level skill profiles |
| 3 | `essential_skills.csv` | — | — | Skill / O*NET code | — | Task/skill taxonomy (likely occupational) |
| 4 | `software_skills.csv` | — | — | Software / O*NET code | — | Software tool taxonomy (likely occupational) |
| 5 | `Cleaned_HR_Data_Analysis.csv` | — | — | ID col → see step 6 | — | Performance/HR analysis |
| 6 | `Employee_Performance_Dataset.csv` | — | — | ID col → see step 6 | — | Employee performance records |
| 7 | `employee_performance_pro.csv` | — | — | ID col → see step 6 | — | Performance extended (pro) |

In [62]:
# PROGRAMMATIC SUMMARY TABLE — live values from loaded dataframes

def top_missing_col(df):
    pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
    if pct.iloc[0] == 0:
        return 'none', 0.0
    return pct.index[0], round(pct.iloc[0], 1)

def likely_pk(df):
    id_like = [c for c in df.columns if 'id' in c.lower()]
    if not id_like:
        return 'none detected'
    return max(id_like, key=lambda c: df[c].nunique())

summary_rows = []
for label, df in [
    ('employee_attrition',           attrition),
    ('occupation_data',              occ),
    ('essential_skills',             ess),
    ('software_skills',              sw),
    ('Cleaned_HR_Data_Analysis',     hr_clean),
    ('Employee_Performance_Dataset', perf_ds),
    ('employee_performance_pro',     perf_pro),
]:
    mc, mp = top_missing_col(df)
    summary_rows.append({
        'Dataset':         label,
        'Rows':            df.shape[0],
        'Cols':            df.shape[1],
        'Likely PK':       likely_pk(df),
        'Top Missing Col': mc,
        'Top Missing %':   mp,
        'Engagement Cols': len(count_engagement_cols(df)),
    })

summary_df = pd.DataFrame(summary_rows).set_index('Dataset')
display(summary_df)

,Rows,Cols,Likely PK,Top Missing Col,Top Missing %,Engagement Cols
Dataset,,,,,,
employee_attrition,1470,35,none detected,none,0.00,4
occupation_data,1016,3,none detected,none,0.00,0
essential_skills,18200,15,Element ID,Not Relevant,50.00,0
software_skills,31821,7,Element ID,none,0.00,0
Cleaned_HR_Data_Analysis,2845,28,Employee ID,none,0.00,4
Employee_Performance_Dataset,5000,13,Employee ID,none,0.00,0
employee_performance_pro,500,24,EmployeeID,CustomerSatisfaction,63.80,2

In [63]:
# EVIDENCE-DRIVEN RECOMMENDATION
# Scoring: overlap with attrition[EmployeeNumber] weighted 60%,
#          engagement/satisfaction column count weighted 40%.
# No merge is performed here.

print('=' * 72)
print('RECOMMENDATION: Which performance file(s) to carry into data/processed/')
print('=' * 72)

_perf_map = {
    'Cleaned_HR_Data_Analysis':     hr_clean,
    'Employee_Performance_Dataset': perf_ds,
    'employee_performance_pro':     perf_pro,
}

scores = {}
for fname, df in _perf_map.items():
    eng_cols     = len(count_engagement_cols(df))
    results      = overlap_results.get(fname, [])
    best_overlap = max((r['pct_of_attrition_anchor'] for r in results), default=0.0)
    score        = best_overlap * 0.6 + eng_cols * 0.4
    scores[fname] = {
        'best_overlap_pct': best_overlap,
        'engagement_cols':  eng_cols,
        'composite_score':  round(score, 2),
    }
    print(f'  {fname}')
    print(f'    Best ID overlap with attrition[EmployeeNumber] : {best_overlap:.1f}%')
    print(f'    Engagement / satisfaction columns              : {eng_cols}')
    print(f'    Composite score  (overlap*0.6 + eng_cols*0.4) : {score:.2f}')
    print()

winner = max(scores, key=lambda k: scores[k]['composite_score'])

print('-' * 72)
print(f'TOP RECOMMENDATION --> {winner}')
print()
print('Rationale:')
print('  1. ID OVERLAP: A non-zero overlap % with attrition[EmployeeNumber] confirms')
print('     the files share actual employee records, making a future join sound.')
print('     Files with 0% overlap are EXTERNAL reference tables, not row-level')
print('     join candidates, and must NOT be merged on ID in Step 3.')
print()
print('  2. ENGAGEMENT RICHNESS: More engagement/satisfaction columns means richer')
print('     feature signal for modelling attrition, retention risk, and burnout.')
print()
print('  3. If ALL three files score 0% overlap (e.g. fully synthetic data),')
print('     select by highest engagement col count + lowest % missing, and flag')
print('     explicitly in the Step 2 data dictionary that no verified join key')
print('     exists -- the feature engineering step must create a synthetic bridge.')
print('=' * 72)

========================================================================
RECOMMENDATION: Which performance file(s) to carry into data/processed/
========================================================================
  Cleaned_HR_Data_Analysis
    Best ID overlap with attrition[EmployeeNumber] : 49.7%
    Engagement / satisfaction columns              : 4
    Composite score  (overlap*0.6 + eng_cols*0.4) : 31.44

  Employee_Performance_Dataset
    Best ID overlap with attrition[EmployeeNumber] : 0.0%
    Engagement / satisfaction columns              : 0
    Composite score  (overlap*0.6 + eng_cols*0.4) : 0.00

  employee_performance_pro
    Best ID overlap with attrition[EmployeeNumber] : 25.6%
    Engagement / satisfaction columns              : 2
    Composite score  (overlap*0.6 + eng_cols*0.4) : 16.19

------------------------------------------------------------------------
TOP RECOMMENDATION --> Cleaned_HR_Data_Analysis

Rationale:
  1. ID OVERLAP: A non-zero overlap % with attrition[EmployeeNumber] confirms
     the files share actual employee records, making a future join sound.
     Files with 0% overlap are EXTERNAL reference tables, not row-level
     join candidates, and must NOT be merged on ID in Step 3.

  2. ENGAGEMENT RICHNESS: More engagement/satisfaction columns means richer
     feature signal for modelling attrition, retention risk, and burnout.

  3. If ALL three files score 0% overlap (e.g. fully synthetic data),
     select by highest engagement col count + lowest % missing, and flag
     explicitly in the Step 2 data dictionary that no verified join key
     exists -- the feature engineering step must create a synthetic bridge.
========================================================================